### ISSUE TITLE
cannot stop scroll onWheel

### ISSUE THREAD

**Issue by t4sk** [t4sk/react-canvas-time-series#45]

**Comment by t4sk** [comment]
Solutions
```css
body {
   overflow: hidden
}
```

Alternative
```js
document.body.style.overflow = "hidden"
```
